name: Derek Bogdan Photography
favicon: null
layout_spectrum: 0.940360717009753
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#41464c'
    - '#ab9b8c'
    - '#cabdad'
    - '#756b5f'
  brandStrength: 0.46670964057557285
  lightness: 0.9144546082243323
  saturation: 0.5531633929349482
  rhythmicContrast: 0.7556031926069409
purpose: []
