name: Derek Bogdan Photography
favicon: null
layout_spectrum: 0.940360717009753
typography_spectrum: 0.7905353019014001
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.46670964057557285
  lightness: 0.9144546082243323
  saturation: 0.5531633929349482
  rhythmicContrast: 0.7556031926069409
purpose: []
